### ISSUE TITLE
Icons in PF2e appearing larger than intended

### ISSUE THREAD

**Issue by Arkensald** [etiquettestartshere/chatedit#17] opened 2024-11-18 00:45 UTC
Hiya - I've tested this issue and it occurs only when ChatEdit is active and no other mod is on. Here's a screenshot of the issue:

![ChatEdit](https://github.com/user-attachments/assets/b080db74-58d8-4fa1-b817-ac6c734ce1e6)

While ChatEdit is active, the icons native to PF2e are resized to be much larger than normal. This happens with all icons, not just the example I've provided.

**Comment by etiquettestartshere** [comment] 2024-11-18 02:32
Can you please provide clear reproduction steps. I barely understand how to use this system lol. The only things I can print to chat with icons seem normal sized.

**Comment by etiquettestartshere** [comment] 2024-11-18 02:34
There also seems to be a discrepancy in your screenshots with mystery-man.svg icon appearing in one and not the other. Is that related?

**Comment by Arkensald** [comment] 2024-11-18 02:42
Hi there - mystery-man.svg icon is unrelated. Here are the replication steps for the pictures I've provided, however the issue happens with a variety of item-based interactions

In pf2e, give a player character a steel shield (located in the compendium). In the actions tab of the character sheet, equip the shield and then click the button that says 'raise'. I'll provide a screenshot below.

![ChatEdit 2](https://github.com/user-attachments/assets/ded3fa54-74c2-4102-a682-f32261ab6f9a)

Let me know if there's anything else I can do to help

**Comment by etiquettestartshere** [comment] 2024-11-18 02:44
For me, hitting 'RAISE' does not even print a chat card. Is there a setting I must enabled?

**Comment by Arkensald** [comment] 2024-11-18 03:10
Thanks for the quick response! I apologize, I'm having trouble finding any specific setting. I reset all the setting to default and it still prints a chat card.

**Comment by etiquettestartshere** [comment] 2024-11-18 03:10
its alright, websterguy helped me: it only appears in combat. basically, this kind of message has nothing to distinguish it, so i have to run a string compare. should be fixed in a moment.

**Closed** 2024-11-18 03:11 UTC
Labels: bug, system
